### ISSUE TITLE
How to find more wonderful effects?

### ISSUE THREAD

**Issue by jackleibest** [numberwolf/FFmpeg-Plus-OpenGL#13]
This is a very great repo. And how can we get more brilliant video filters?

**Comment by numberwolf** [comment]
I will build a web application , you can make your own wanderful effects and output the shader for this filter~

**Comment by numberwolf** [comment]
maybe this week~ 

my friend , can u give me a star~

**Comment by numberwolf** [comment]
I have make a web application, you can make your wonderful shaders with https://www.zzsin.com/shaderplus.html
