### ISSUE TITLE
git apply 失败了

### ISSUE THREAD

**Issue by k713927** [numberwolf/FFmpeg-Plus-OpenGL#23]
error: patch failed: libavfilter/allfilters.c:444
error: libavfilter/allfilters.c: patch does not apply

**Comment by numberwolf** [comment]
这样子，
1）直接用 patch 打进去就好了。
2）如果patch打不进去，其实按照diff修改就可以了，不到十行。

**Comment by k713927** [comment]
好的，明白，感谢
