### ISSUE TITLE
方便增加透明通道的支持吗

### ISSUE THREAD

**Issue by k713927** [numberwolf/FFmpeg-Plus-OpenGL#24]
如果一个视频底层有背景视频的，
类似转场这个 https://github.com/transitive-bullshit/ffmpeg-gl-transition/pull/60  ，
改动的说明在这里 https://blog.csdn.net/Asa_Ho/article/details/116096500?spm=1001.2014.3001.5501

**Comment by asa-charles-ho** [comment]
> 如果一个视频底层有背景视频的，
> 类似转场这个 [transitive-bullshit/ffmpeg-gl-transition#60](https://github.com/transitive-bullshit/ffmpeg-gl-transition/pull/60) ，
> 改动的说明在这里 https://blog.csdn.net/Asa_Ho/article/details/116096500?spm=1001.2014.3001.5501

#25 可以参考这里，刚好最近改了一下

**Comment by numberwolf** [comment]
> > 如果一个视频底层有背景视频的，
> > 类似转场这个 [transitive-bullshit/ffmpeg-gl-transition#60](https://github.com/transitive-bullshit/ffmpeg-gl-transition/pull/60) ，
> > 改动的说明在这里 https://blog.csdn.net/Asa_Ho/article/details/116096500?spm=1001.2014.3001.5501
> 
> #25 可以参考这里，刚好最近改了一下

已merge
