### ISSUE TITLE
使用plusglshader滤镜为分辨率9:16的视频添加特效，效果异常

### ISSUE THREAD

**Issue by smok56888** [numberwolf/FFmpeg-Plus-OpenGL#30]
# 问题描述
使用plusglshader对视频进行特效处理时，当**原始视频为9:16分辨率格式时，结果视频的显示效果异常**。
在其他分辨率如3:4、4:3、16:9等尺寸时，效果正常展示。

# 执行参数
* 原始视频1：v_3#4_origin.mp4，分辨率为480*640
* 原始视频2：v_9#16_origin.mp4，分辨率为360*640
* 特效文件：使用教程中提供的split_interval_shader特效，未修改https://github.com/numberwolf/FFmpeg-Plus-OpenGL/blob/main/Plus-GL-Shader/gl/split_interval_shader.gl
* 执行命令如下：
`ffmpeg -i v_3#4_origin.mp4 -filter_complex "plusglshader=sdsource=splitinterval.fs:vxsource=splitinterval.vs" -an -loglevel 24 -pix_fmt yuv420p  -y v_3#4_result.mp4`

# 测试资源地址
链接: https://pan.baidu.com/s/1JrrnFPbhRERs53hb-VWABA  密码: snuj

**Comment by numberwolf** [comment]
这样，不要用多屏幕外接跑服务。

先把视频scale程你屏幕大小，然后渲染，然后再scale回去
