### ISSUE TITLE
mac os Conversion failed!

### ISSUE THREAD

**Issue by chenjian03272** [numberwolf/FFmpeg-Plus-OpenGL#31]
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] doing vf_fadeglshader build_shader
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] doing vf_fadeglshader build_shader glCreateShader glIsShader FAILED!
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] doing vf_fadeglshader update_program failed!
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] Failed to configure input pad on Parsed_fadeglshader_1
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] start vf_fadeglshader uninit action
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] doing vf_fadeglshader check window
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] doing vf_fadeglshader gl delete operations
[Parsed_fadeglshader_1 @ 0x7fce67f6e4c0] finished vf_fadeglshader
Error reinitializing filters!
Failed to inject frame into filter network: Operation not permitted
Error while processing the decoded data for stream #0:0
[AVIOContext @ 0x7fce67f12300] Statistics: 0 seeks, 0 writeouts
[AVIOContext @ 0x7fce67f060c0] Statistics: 262144 bytes read, 0 seeks
Conversion failed!

**Comment by numberwolf** [comment]
```
 glCreateShader glIsShader FAILED!
```

是不是shader写错了
