### ISSUE TITLE
/usr/bin/xvfb-run: line 181: 46303 Segmentation fault 

### ISSUE THREAD

**Issue by GikkiAres** [numberwolf/FFmpeg-Plus-OpenGL#33]
[Environment]
1,OS: centos 8
2,vf_plusglshader has successfully installed.
3,No video card and installed xvfb

[Command]
$ xvfb-run -a --server-args="-screen 0 1280x720x24 -ac -nolisten tcp -dpi 96 +extension RANDR" \ ./ffmpeg -v debug \ -i 0.mp4 \ -vf plusglshader \ -y output.mp4

[Output]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/13636974/171566260-e2e6cb75-964e-4e56-95d0-bfb604452d7f.png">

[Question]
Why the transcode failed?

**Comment by GikkiAres** [comment]
`yum install -y glew glew-devel
yum install -y glfw glfw-devel
yum install -y mesa-dri-drivers

yum install -y libGLEW*
yum install -y mesa
yum install -y mesa-libGLU mesa-libGLU-devel
yum install -y libXfont*`

Some dependency is not installed.
Transcode complete successfully after installing all dependencies!

**Comment by numberwolf** [comment]
good~
